config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/:user_id/followers', to: 'users#followers'
  put '/users/:user_id/followers', to: 'users#follow'
  delete '/users/:user_id/followers', to: 'users#unfollow'
  root to: "users#index"
  resources :users, :only => [:new, :create, :destroy, :index] do
    resources :shouts, :only => [:new, :create, :show, :destroy, :index]
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/shout.rb
class Shout < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shouts

  has_many :relationships, foreign_key: "follower_id"
  has_many :following, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
           class_name: "Relationship"
  has_many :followers, through: :reverse_relationships, source: :follower


  validates :username, presence: true, uniqueness: true,
            format: { with: /[a-zA-Z0-9]{4,20}/,
                      message: "Must be between 4 and 20 characters."}


  # def follow!(user)
  #   self.following.where("relationships.followed_id => ?", user.id).first_or_create!
  # end

   def follow!(other_user)
     self.relationships.create!(followed_id: other_user.id)
   end

  def unfollow!(user)
    # NOTE: This throws an exception if we aren't following user
    self.following.where("relationships.followed_id" => user.id).destroy!
  end

  def follows?(user)
    self.following.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_sign_up_params, if: :devise_controller?
  
  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def index
    @shouts = current_user.shouts
    render :index
  end

  def show
    @shout = Shout.find(params[:id])
    render :show
  end

  def new
    @shout = Shout.new
    render :new
  end

  def create
    @shout = Shout.new(shout_params)
    @shout.user_id = params[:user_id]
    @shout.save!
  end

  def destroy
    @shout.destroy
    redirect_to root_path, notice: 'Boom. Shout destroyed!'
  end

  private

  def set_shout
    @shout = Shout.find(params[:user_id])
  end

  def shout_params
    params.require(:shout).permit(:body, :user_id)
  end

  def redirect_unless_user_match
    unless @user == current_user
      flash[:notice] = "You cannot perform actions on #{@user.username}"
      redirect_to :root
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to :action => :index
  end

  def index
    @users = User.all
    render :index
  end

  def destroy
    @user = User.find(params[:id])
    if current_user == @user
      @user.destroy
      redirect_to users_path, notice: "Your user was deleted!"
    else
      flash[:alert] = "You are only allowed to delete your account!!"
      redirect_to :root
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouthouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <%= link_to "Sign Out" , destroy_user_session_path, method: :delete %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/shouts/_form.html.erb
<%= form_for new_user_shout_path do |f| %>

  <div class="field">
    <%= f.label 'Body' %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shouts/index.html.erb
<h1> Listing Shouts</h1>

<% current_user.shouts.each do |shout| %>
    <div class="shout">
        <%= shout.body %>
    </div>
<% end %>

<br>

<%= link_to 'New Shout', new_user_shout_path %>

app/views/shouts/new.html.erb
<h1> New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_shouts_path %>

app/views/shouts/show.html.erb
<p class="notice"><%= notice %></p>

<%= render :index %> 

<%= link_to 'Back', user_shouts_path %>

app/views/users/followers.html.erb
<h1>Hello, <%=current_user.username %>. Here's your list of followers: </h1>

<br>

<ul>
  <% current_user.followers.each do |follower| %>
  <li> <%= follower.username %> ; <%= follower.email %> </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Hello, Tweethouse Users!</h1>

<ul>
  <% @users.each do |user| %>
    <li>Hello, <%= user.username %>.
      Actions:
      <%= link_to "Your Shouts", user_shouts_path(user) %> |
      <%= link_to "Delete Account", user_path(user), method: :delete %> |
      <%= link_to "Create Shout", new_user_shout_path(user) %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back', :back %> | <%= link_to 'New User', new_user_registration_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label 'Username' %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label 'Password' %>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>